server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fundoo_notes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: fundoo-notes

jwt:
  secret:
    key: FundooNotesSecretKeyForJWTGeneration2024
  expiration:
    ms: 86400000

logging:
  level:
    root: INFO
    com.fundoonotes: DEBUG
